"""add_dispatch_log_table

Revision ID: 7fc8d644de92
Revises: e4cd33464577
Create Date: 2026-03-21 00:19:33.577505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc8d644de92'
down_revision: Union[str, Sequence[str], None] = 'e4cd33464577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('response_code', sa.SmallInteger(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_log_alert_id'), 'dispatch_log', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_log_alert_id'), table_name='dispatch_log')
    op.drop_table('dispatch_log')
    # ### end Alembic commands ###
