"""add_partial_unique_index_alerts

Revision ID: e5cbb98b4af2
Revises: 7fc8d644de92
Create Date: 2026-03-21 01:13:37.410210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cbb98b4af2'
down_revision: Union[str, Sequence[str], None] = '7fc8d644de92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_active_alert', 'alerts', ['user_id', 'ticker', 'target_price', 'condition'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_alert', table_name='alerts', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###
